apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_HOST"
              value: "color.appmeshload.svc.cluster.local"
            - name: "FORWARD_PORT"
              value: "8090"
            - name: "TEXT"
              value: "front"
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: color
    version: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: appmeshload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color
      version: blue
  template:
    metadata:
      labels:
        app: color
        version: blue
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_PATH"
              value: "/get"
            - name: "TEXT"
              value: "blue"
---
apiVersion: v1
kind: Service
metadata:
  name: red
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: color
    version: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  namespace: appmeshload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color
      version: red
  template:
    metadata:
      labels:
        app: color
        version: red
    spec:
      containers:
        - name: app
          image: zhaojiew/appmeshload:latest
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_PATH"
              value: "/get"
            - name: "TEXT"
              value: "red"
---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http