apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: front
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-v1
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
      version: v1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "TEXT"
              value: "front"
            - name: "MULTIHOST"
              value: "http://color.appmeshload.svc.cluster.local:8090/forward,http://animal.appmeshload.svc.cluster.local:8090/get"
---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: color
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-v1
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: v1
  template:
    metadata:
      labels:
        app: color
        version: v1
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_HOST"
              value: "fruit.appmeshload.svc.cluster.local"
            - name: "FORWARD_PATH"
              value: "/get"
            - name: "TEXT"
              value: "color-v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-v2
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: v2
  template:
    metadata:
      labels:
        app: color
        version: v2
    spec:
      containers:
        - name: app
          image: zhaojiew/appmeshload:latest
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_HOST"
              value: "fruit.appmeshload.svc.cluster.local"
            - name: "FORWARD_PATH"
              value: "/get"
            - name: "TEXT"
              value: "color-v2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-v3
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: v3
  template:
    metadata:
      labels:
        app: color
        version: v3
    spec:
      containers:
        - name: app
          image: zhaojiew/appmeshload:latest
          ports:
            - containerPort: 8090
          env:
            - name: "FORWARD_HOST"
              value: "fruit.appmeshload.svc.cluster.local"
            - name: "FORWARD_PATH"
              value: "/get"
            - name: "TEXT"
              value: "color-v3"
# fruit load
---
apiVersion: v1
kind: Service
metadata:
  name: fruit
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: fruit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-v1
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit
      version: v1
  template:
    metadata:
      labels:
        app: fruit
        version: v1
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "TEXT"
              value: "fruit-v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-v2
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit
      version: v2
  template:
    metadata:
      labels:
        app: fruit
        version: v2
    spec:
      containers:
        - name: app
          image: zhaojiew/appmeshload:latest
          ports:
            - containerPort: 8090
          env:
            - name: "TEXT"
              value: "fruit-v2"
# animal load
---
apiVersion: v1
kind: Service
metadata:
  name: animal
  namespace: appmeshload
spec:
  ports:
    - port: 8090
      name: http
  selector:
    app: animal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-v1
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animal
      version: v1
  template:
    metadata:
      labels:
        app: animal
        version: v1
    spec:
      containers:
        - name: app
          image:  zhaojiew/appmeshload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: "TEXT"
              value: "animal-v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-v2
  namespace: appmeshload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animal
      version: v2
  template:
    metadata:
      labels:
        app: animal
        version: v2
    spec:
      containers:
        - name: app
          image: zhaojiew/appmeshload:latest
          ports:
            - containerPort: 8090
          env:
            - name: "TEXT"
              value: "animal-v2"